use axum::{Router, routing::{post, get}};

pub fn build_router() -> Router {
	Router::new()
		.route("/events", get(crate::handlers::events))
		.route("/get_categories", post(crate::handlers::get_categories))
		.route("/list_plugins", post(crate::handlers::list_plugins))
		.route("/get_selected_profile", post(crate::handlers::get_selected_profile))
		.route("/set_selected_profile", post(crate::handlers::set_selected_profile))
		.route("/get_devices", post(crate::handlers::get_devices))
		.route("/create_instance", post(crate::handlers::create_instance))
		.route("/move_instance", post(crate::handlers::move_instance))
		.route("/set_state", post(crate::handlers::set_state))
		.route("/remove_instance", post(crate::handlers::remove_instance))
		.route("/get_build_info", post(crate::handlers::get_build_info))
		.route("/restart", post(crate::handlers::restart))
		.route("/open_url", post(crate::handlers::open_url))
		.route("/install_plugin", post(crate::handlers::install_plugin))
		.route("/remove_plugin", post(crate::handlers::remove_plugin))
		.route("/reload_plugin", post(crate::handlers::reload_plugin))
		.route("/open_log_directory", post(crate::handlers::open_log_directory))
		.route("/show_settings_interface", post(crate::handlers::show_settings_interface))
		.route("/get_profiles", post(crate::handlers::get_profiles))
		.route("/delete_profile", post(crate::handlers::delete_profile))
		.route("/rename_profile", post(crate::handlers::rename_profile))
		.route("/get_applications", post(crate::handlers::get_applications))
		.route("/get_application_profiles", post(crate::handlers::get_application_profiles))
		.route("/set_application_profiles", post(crate::handlers::set_application_profiles))
		.route("/make_info", post(crate::handlers::make_info))
		.route("/open_config_directory", post(crate::handlers::open_config_directory))
		.route("/switch_property_inspector", post(crate::handlers::switch_property_inspector))
		.route("/update_image", post(crate::handlers::update_image))
		.route("/get_settings", post(crate::handlers::get_settings))
		.route("/set_settings", post(crate::handlers::set_settings))
		.route("/get_localisations", post(crate::handlers::get_localisations))
}
